### ISSUE TITLE
yum

### ISSUE THREAD

**Issue by ghost** [ClientPlayground/Melon-Client#6]
.

**Comment by itsnebulalol** [comment]
bro you can see the source what are you talking about

**Comment by ghost** [comment]
Exactly my point. The source is available so there is no need to obfuscate the JAR in your releases.
lol?
Why would the jar in releases be obf...

**Comment by Annunciate** [comment]
ok
ratio

**Comment by itsnebulalol** [comment]
> Exactly my point. The source is available so there is no need to obfuscate the JAR in your releases. lol? Why would the jar in releases be obf...

bozo we didn't obf it it was already obfed
the source is a remapped/deobf'd version

**Comment by laika-cosmonaut** [comment]
average melon client dev

**Comment by ghost** [comment]
Bro u good? The release JAR is just the original JAR file that was obfuscated by Kaimson.

**Comment by itsnebulalol** [comment]
can you please tell me where the issue is

**Comment by ghost** [comment]
You talkin to me or darkprobe?

**Comment by itsnebulalol** [comment]
> You talkin to me or darkprobe?

darkprobe
