### ISSUE TITLE
error when running setupDecomp workspace

### ISSUE THREAD

**Issue by agastyasandhuja** [ClientPlayground/Melon-Client#7]
getting the error
```
Execution failed for task ':fixMcSources'.
> com.cloudbees.diff.PatchException: Cannot find hunk target
```
I've tried going online and attempted many fixes through GitHub (alr existing errors) and stackoverflow (like full clean and stuff) but it has not helped me fix the issue so I'm here asking now. 
I can give any files + full stack trace if you need
eclipse (tried intellij same)
osx later version
java 8
already tried everything I can

**Comment by itsnebulalol** [comment]
It’s probably broken, I have no idea
